[general]
email = "kcamulya603@gmail.com"

[api_keys]
GOOGLE_API_KEY = "AIzaSyCQDm-jvpXkwWZjGi0fY6vDqznYIXOcMjs"

[mongodb]
MONGO_URI = "mongodb+srv://Amulya:<amulya@123>@cluster0.in7ty3e.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"